version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 2
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "drupal/core-composer-scaffold"
        update-types: ["version-update:semver-major"]
      - dependency-name: "drupal/core-project-message"
        update-types: ["version-update:semver-major"]
      - dependency-name: "drupal/core-recommended"
        update-types: ["version-update:semver-major"]
