name: Build, deploy and test
on:
  push:
    branches:
      - main
      - qa
  pull_request:

jobs:
  build_and_deploy:
    name: Build and deploy
    uses: UCEAP/actions/.github/workflows/build_and_deploy.yml@main
    with:
      TERMINUS_SITE: ${{ vars.TERMINUS_SITE }}
      OP_VAULT: ${{ vars.OP_VAULT }}
      JIRA_PROJECT_KEY: ${{ vars.JIRA_PROJECT_KEY }}
      JIRA_EMAIL: ${{ vars.JIRA_EMAIL }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  e2e_test:
    name: E2E Test
    uses: UCEAP/actions/.github/workflows/e2e_test.yml@main
    needs: [build_and_deploy]
    with:
      TERMINUS_SITE: ${{ vars.TERMINUS_SITE }}
      TERMINUS_ENV: ${{ needs.build_and_deploy.outputs.terminus_env }}
      OP_VAULT: ${{ vars.OP_VAULT }}
      CYPRESS_PROJECT_ID: ${{ vars.CYPRESS_PROJECT_ID }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
