name: Cleanup multidevs
on:
  pull_request:
    types: [closed]
defaults:
  run:
    shell: bash

jobs:
  cleanup_multidevs:
    name: Cleanup multidevs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/uceap/devcontainer-drupal:main
    steps:
      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TERMINUS_TOKEN: op://secrets-template/pantheon-terminus/credential
      - name: Prune stale multidev environments
        env:
          TERMINUS_SITE: ${{ vars.TERMINUS_SITE }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: uceap cleanup-multidevs
